# encoding=UTF-8
spring.application.name=backend

spring.datasource.url=jdbc:mysql://db.sudaru.dpdns.org:3306/ego?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
spring.datasource.username=your_account
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.max-lifetime=500000
# application.yml
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.web.resources.static-locations=file:./img,classpath:/static

logging.file.path=./logs
logging.file.name=./log/ego.log
# JWT
jwt.secret=ego2025ThatWasAdifficultStuffIamTireForThatIfSomeOneLookAtThisSentencePleaseDoNotReadThat
jwt.expiration=86400000
server.port=8081
file.upload-dir=img
external.image.path=./
mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.type-aliases-package=com.example.demo.entity